# SPDX-FileCopyrightText: 2022 Alec Delaney
#
# SPDX-License-Identifier: MIT

repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        name: Detect secrets
  - repo: https://github.com/fsfe/reuse-tool
    rev: v2.1.0
    hooks:
      - id: reuse
        name: Ensure REUSE compatibility
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        name: Check YAML
      - id: check-toml
        name: Check TOML
      - id: check-json
        name: Check JSON
      - id: mixed-line-ending
        name: Prevent mixed line endings
      - id: requirements-txt-fixer
        name: Fix requirements.txt
      - id: end-of-file-fixer
        name: Fix end of files
      - id: trailing-whitespace
        name: Trim trailing whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.11
    hooks:
      - id: ruff-format
        name: Format via ruff
      - id: ruff
        name: Check via ruff
        args: [--fix]
