# SPDX-FileCopyrightText: 2022 Alec Delaney
#
# SPDX-License-Identifier: MIT

name: Release CI

on:
  release:
    types: [published]

jobs:
  upload-pypi:
    runs-on: ubuntu-latest
    steps:
    - name: Set up latest Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Check Python version
      run: |
        python3 --version
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install dependencies for building
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade build twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.pypi_username }}
        TWINE_PASSWORD: ${{ secrets.pypi_password }}
      run: |
        for file in $(find -not -path "./.*" -not -path "./docs*" \( -name "*.py" -o -name "*.toml" \) ); do
            sed -i -e "s/0.0.0+auto.0/${{github.event.release.tag_name}}/" $file;
        done;
        python -m build
        twine upload dist/*
