# SPDX-FileCopyrightText: 2022 Alec Delaney
#
# SPDX-License-Identifier: MIT

name: Release CI

on:
  release:
    types: [published]

jobs:
  upload-pypi:
    runs-on: ubuntu-latest
    steps:
    - name: Set up latest Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Install dependencies for building
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade build twine
    - name: Set version for release
      run: |
        echo ${{github.event.release.tag_name}} > VERSION
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.pypi_username }}
        TWINE_PASSWORD: ${{ secrets.pypi_password }}
      run: |
        python -m build
        twine upload dist/*
